

services:

  postgres:
    image: postgres:17
    container_name: coreerp_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: coreerp

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: coreerp_backend

    restart: always

    depends_on:
      - postgres

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend

    container_name: coreerp_frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run dev -- --host

volumes:
  postgres_data: