"""adiciona categorias financeiras

Revision ID: 1642469f38b1
Revises: dfe957eb93e5
Create Date: 2026-07-25 02:15:34.926149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1642469f38b1'
down_revision: Union[str, Sequence[str], None] = 'dfe957eb93e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_financeiras_empresa_id'), 'categorias_financeiras', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_categorias_financeiras_id'), 'categorias_financeiras', ['id'], unique=False)
    op.add_column('lancamentos_financeiros', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lancamentos_financeiros_categoria_id'), 'lancamentos_financeiros', ['categoria_id'], unique=False)
    op.create_foreign_key(None, 'lancamentos_financeiros', 'categorias_financeiras', ['categoria_id'], ['id'])
    op.drop_column('lancamentos_financeiros', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos_financeiros', sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lancamentos_financeiros', type_='foreignkey')
    op.drop_index(op.f('ix_lancamentos_financeiros_categoria_id'), table_name='lancamentos_financeiros')
    op.drop_column('lancamentos_financeiros', 'categoria_id')
    op.drop_index(op.f('ix_categorias_financeiras_id'), table_name='categorias_financeiras')
    op.drop_index(op.f('ix_categorias_financeiras_empresa_id'), table_name='categorias_financeiras')
    op.drop_table('categorias_financeiras')
    # ### end Alembic commands ###
