"""create tabela produtos

Revision ID: 3eb7db5ae700
Revises: a48739bdb308
Create Date: 2026-07-17 03:01:04.525351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb7db5ae700'
down_revision: Union[str, Sequence[str], None] = 'a48739bdb308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('produtos')
    # ### end Alembic commands ###
