"""cria tabela imagens produto

Revision ID: 4f96017a1d86
Revises: b2e9997eb0cc
Create Date: 2026-07-20 00:32:36.961665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f96017a1d86'
down_revision: Union[str, Sequence[str], None] = 'b2e9997eb0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    op.execute("""
    UPDATE produtos
    SET estoque = 0
    WHERE estoque IS NULL
    """)
    op.alter_column(
        'produtos', 
        'estoque',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        nullable=False
    )
    
    op.execute("""
    UPDATE produtos
    SET estoque_minimo = 0
    WHERE estoque_minimo IS NULL
    """)
    op.alter_column(
        'produtos',
        'estoque_minimo',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        nullable=False
    )

    op.execute("""
    UPDATE produtos
    SET estoque_maximo = 0
    WHERE estoque_maximo IS NULL
    """)
    op.alter_column(
        'produtos', 
        'estoque_maximo',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        nullable=False
    )
    op.execute("""
    UPDATE produtos
    SET custo_medio = 0
    WHERE custo_medio IS NULL
    """)
    op.alter_column(
        'produtos',
        'custo_medio',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'custo_medio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('produtos', 'estoque_maximo',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'estoque_minimo',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'estoque',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_table('produto_imagens')
    # ### end Alembic commands ###
