"""add empresa_id produtos

Revision ID: 7b57aaaa0b8e
Revises: 5965dff94cd8
Create Date: 2026-07-17 02:06:54.326443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b57aaaa0b8e'
down_revision: Union[str, Sequence[str], None] = '5965dff94cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
