"""adiciona campos profissionais produto

Revision ID: b71844930427
Revises: cd8114097649
Create Date: 2026-07-20 00:02:37.171985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71844930427'
down_revision: Union[str, Sequence[str], None] = 'cd8114097649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque_minimo', sa.Integer(), nullable=True))
    op.add_column('produtos', sa.Column('estoque_maximo', sa.Integer(), nullable=True))
    op.add_column('produtos', sa.Column('peso', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('altura', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('largura', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('comprimento', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('localizacao', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('custo_medio', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('ultima_entrada', sa.DateTime(), nullable=True))
    op.add_column('produtos', sa.Column('ultima_saida', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'ultima_saida')
    op.drop_column('produtos', 'ultima_entrada')
    op.drop_column('produtos', 'custo_medio')
    op.drop_column('produtos', 'localizacao')
    op.drop_column('produtos', 'comprimento')
    op.drop_column('produtos', 'largura')
    op.drop_column('produtos', 'altura')
    op.drop_column('produtos', 'peso')
    op.drop_column('produtos', 'estoque_maximo')
    op.drop_column('produtos', 'estoque_minimo')
    # ### end Alembic commands ###
