"""campos_produto

Revision ID: cd8114097649
Revises: 2f4fb9e8d1aa
Create Date: 2026-07-19 22:18:28.687696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8114097649'
down_revision: Union[str, Sequence[str], None] = '2f4fb9e8d1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('codigo_interno', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('codigo_barras', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('marca', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('unidade', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'descricao')
    op.drop_column('produtos', 'unidade')
    op.drop_column('produtos', 'marca')
    op.drop_column('produtos', 'codigo_barras')
    op.drop_column('produtos', 'codigo_interno')
    op.drop_column('produtos', 'categoria')
    # ### end Alembic commands ###
