"""financeiro_v2

Revision ID: dfe957eb93e5
Revises: b2ed187650e4
Create Date: 2026-07-24 21:22:45.670898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe957eb93e5'
down_revision: Union[str, Sequence[str], None] = 'b2ed187650e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamentos_financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_financeiros_empresa_id'), 'lancamentos_financeiros', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_financeiros_id'), 'lancamentos_financeiros', ['id'], unique=False)
    op.alter_column('clientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_empresa_id'), 'itens_venda', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_venda_id'), 'itens_venda', ['venda_id'], unique=False)
    op.alter_column('movimentos_estoque', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_movimentos_estoque_empresa_id'), 'movimentos_estoque', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimentos_estoque_produto_id'), 'movimentos_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentos_estoque_usuario_id'), 'movimentos_estoque', ['usuario_id'], unique=False)
    op.alter_column('produtos', 'unidade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_produtos_empresa_id'), 'produtos', ['empresa_id'], unique=False)
    op.alter_column('vendas', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_empresa_id'), 'vendas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vendas_usuario_id'), 'vendas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_usuario_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_empresa_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.alter_column('vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendas', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_produtos_empresa_id'), table_name='produtos')
    op.alter_column('produtos', 'unidade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_movimentos_estoque_usuario_id'), table_name='movimentos_estoque')
    op.drop_index(op.f('ix_movimentos_estoque_produto_id'), table_name='movimentos_estoque')
    op.drop_index(op.f('ix_movimentos_estoque_empresa_id'), table_name='movimentos_estoque')
    op.alter_column('movimentos_estoque', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_itens_venda_venda_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_empresa_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.alter_column('clientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lancamentos_financeiros_id'), table_name='lancamentos_financeiros')
    op.drop_index(op.f('ix_lancamentos_financeiros_empresa_id'), table_name='lancamentos_financeiros')
    op.drop_table('lancamentos_financeiros')
    # ### end Alembic commands ###
